sudo: false
language: node_js

cache:
    yarn: true
    directories:
        - node_modules

node_js:
    - '8'

env:
    - CXX=g++-4.8
    - AUDIODEV=null

before_install:
    - modprobe snd-dummy

install:
    - npm i -g yarn
    - yarn install -s --no-optional

script:
    - yarn test-front
    - yarn test-core

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libfontconfig1-dev
            # dependent by `av`
            - libasound2-dev
            - alsa-utils
            - alsa-oss
